"""Suggestion engine for generating fix recommendations.

Implements rule-based fix mapping from data_doctor.md Section 8:
- Pipeline Failure → Rerun pipeline
- Schema Change → Update schema
- Stale Data → Force backfill
- Data Quality → Quarantine data

Phase 4 Implementation.
"""
from src.constants import AnomalyType, FixAction
from src.schemas import AnomalyDetail, SuggestedFix


# Rule-based mapping: Anomaly Type -> Fix Action
FIX_MAPPING = {
    AnomalyType.PIPELINE_FAILURE: {
        "action": FixAction.RERUN_PIPELINE,
        "description_template": "Rerun the failed {target} pipeline from last checkpoint."
    },
    AnomalyType.SCHEMA_CHANGE: {
        "action": FixAction.UPDATE_SCHEMA,
        "description_template": "Remove the deleted column reference from downstream views/DBT models for {target}."
    },
    AnomalyType.STALE_DATA: {
        "action": FixAction.FORCE_BACKFILL,
        "description_template": "Trigger a historical backfill DAG to restore missing partitions in {target}."
    },
    AnomalyType.DATA_QUALITY_FAILURE: {
        "action": FixAction.QUARANTINE_DATA,
        "description_template": "Implement data contract validation to drop anomalous rows in {target}."
    }
}


def generate_suggested_fixes(
    primary_cause: AnomalyDetail | None,
    contributing_factors: list[AnomalyDetail]
) -> list[SuggestedFix]:
    """
    Generate suggested fixes based on detected anomalies.
    
    CRITICAL: Always returns a non-empty list of structured fix objects.
    
    Args:
        primary_cause: Primary root cause anomaly
        contributing_factors: Contributing anomalies
    
    Returns:
        List of SuggestedFix objects (always non-empty)
    """
    fixes: list[SuggestedFix] = []
    
    # Generate fix for primary cause
    if primary_cause:
        fix = _create_fix_for_anomaly(primary_cause)
        if fix:
            fixes.append(fix)
    
    # Generate fixes for contributing factors
    for anomaly in contributing_factors:
        fix = _create_fix_for_anomaly(anomaly)
        if fix:
            fixes.append(fix)
    
    # Ensure we always return at least one fix
    if not fixes:
        fixes.append(SuggestedFix(
            action=FixAction.RERUN_PIPELINE,
            target="unknown",
            description="Manual investigation required. Check pipeline logs and data quality metrics."
        ))
    
    return fixes


def _create_fix_for_anomaly(anomaly: AnomalyDetail) -> SuggestedFix | None:
    """
    Create a fix suggestion for a single anomaly.
    
    Args:
        anomaly: Detected anomaly
    
    Returns:
        SuggestedFix or None if no mapping exists
    """
    mapping = FIX_MAPPING.get(anomaly.type)
    if not mapping:
        return None
    
    description = mapping["description_template"].format(target=anomaly.name)
    
    return SuggestedFix(
        action=mapping["action"],
        target=anomaly.name,
        description=description,
        sql_script=None,  # Will be generated by AI layer in Phase 5
        markdown_details=None  # Will be generated by AI layer in Phase 5
    )
